<?php

namespace CommonBundle\Repository;

/**
 * GiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GiteRepository extends \Doctrine\ORM\EntityRepository
{
}
