front_search:
    resource: "@FrontSearchBundle/Controller/"
    type:     annotation
    prefix:   /

front_home:
    resource: "@FrontHomeBundle/Controller/"
    type:     annotation
    prefix:   /

front_gite:
    resource: "@FrontGiteBundle/Controller/"
    type:     annotation
    prefix:   /gite

common_user:
    resource: "@CommonUserBundle/Controller/"
    type:     annotation
    prefix:   /user

common_entity:
    resource: "@CommonEntityBundle/Controller/"
    type:     annotation
    prefix:   /entity

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"