<?php

namespace Common\EntityBundle\Repository;

/**
 * InformationRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
