<?php

namespace Common\EntityBundle\Repository;

/**
 * RentRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
